### ISSUE TITLE
Fieldset [social-media-image-kit::stillat_social_media_images] not found

### ISSUE THREAD

**Issue by mprince2k18** [Stillat/tidal#4]
Facing error after installation.

statamic new my-site stillat/tidal

npm install

npm run build

visited my domain and got this error.

**Comment by mprince2k18** [comment]
@JohnathonKoster can you help me about this case, so that I can fix it.

**Comment by JohnathonKoster** [comment]
Yes, I plan to look into this over the weekend once I have some free time 👍

**Comment by JohnathonKoster** [comment]
I'm having troubles reproducing this using the steps listed. Would you be able to provide the results of

```bash
php please support:details
```

as well as the operating system?

Thanks!

**Comment by mprince2k18** [comment]
sure. here it is.

```shell
Environment
Application Name: Statamic
Laravel Version: 11.35.0
PHP Version: 8.3.14
Composer Version: 2.8.3
Environment: local
Debug Mode: ENABLED
URL: tidal.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 9
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.42.0 Solo

Statamic Addons
mitydigital/feedamic: 2.5.0
statamic/eloquent-driver: 4.19.0
stillat/antlers-components: 2.4.0
stillat/documentation-search: 1.2.1
stillat/social-media-image-kit: 1.3.0
stillat/statamic-attribute-renderer: 1.1.0
stillat/statamic-bard-heading-permalinks: 1.1.0
stillat/statamic-search-report: 1.1.1
stillat/statamic-site-essentials: 1.3.0

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: eloquent
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: file
Sites: eloquent
Taxonomies: eloquent
Terms: eloquent
Tokens: eloquent
```

**Comment by mprince2k18** [comment]
@JohnathonKoster let me know if this is okay.

**Comment by JohnathonKoster** [comment]
Thanks! I was able to confirm this when using the Eloquent storage driver. I'll let you know what I find out!

**Comment by mprince2k18** [comment]
> Thanks! I was able to confirm this when using the Eloquent storage driver. I'll let you know what I find out!

sure. thank you.

**Comment by mprince2k18** [comment]
> Thanks! I was able to confirm this when using the Eloquent storage driver. I'll let you know what I find out!

@JohnathonKoster  Let me know if I help you in any way.

**Comment by JohnathonKoster** [comment]
@mprince2k18 

To resolve this, create a new file at the following location within your project at:

`resources/fieldsets/vendor/social-meida-image-kit/stillat_social_media_images.yaml` with the following contents:

```yaml
title: 'Social Media Images'
fields:
  -
    handle: social_media_images
    field:
      mode: stacked
      reorderable: true
      fullscreen: true
      type: grid
      display: 'Social Media Images'
      icon: grid
      localizable: false
      listable: hidden
      instructions_position: above
      visibility: visible
      replicator_preview: true
      hide_display: false
      fields:
        -
          handle: asset_social_media_image
          field:
            max_files: 1
            mode: list
            container: social_media_images
            restrict: false
            allow_uploads: true
            show_filename: true
            show_set_alt: true
            type: assets
            display: Image
            icon: assets
            localizable: false
            listable: hidden
            instructions_position: above
            visibility: visible
            replicator_preview: true
            hide_display: false
            width: 66
            readonly: true
        -
          handle: social_media_image_type
          field:
            taggable: false
            push_tags: false
            multiple: false
            clearable: false
            searchable: true
            cast_booleans: false
            type: social_media_image_type
            display: 'Social Media Platform'
            icon: social_media_image_type
            localizable: false
            listable: hidden
            instructions_position: above
            visibility: visible
            replicator_preview: true
            hide_display: false
            width: 33
        -
          handle: preserve_image
          field:
            default: false
            type: toggle
            display: 'Preserve Image'
            icon: toggle
            instructions: 'Set this to true to ensure any customized images are not overwritten when updating social media images.'
            localizable: false
            width: 50
            listable: hidden
            instructions_position: above
            visibility: visible
            replicator_preview: true
            hide_display: false

```

Afterwards, you will need to re-import the fieldsets:

```
php please eloquent:import-blueprints
```

When presented with the option "Do you want to import fieldsets? (yes/no)" enter "yes". It appears the Eloquent driver importer does not handle addon fieldsets without them being available within the project root, which is something I will look into separately. Thanks!
